name: aes_crypt_null_safe
description: Dart encryption library for encrypting/decrypting files, plain text and binary data in AES Crypt file format.
version: 3.0.0
homepage: https://github.com/CodingFries/aes_crypt_null_safe
repository: https://github.com/CodingFries/aes_crypt_null_safe

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

# dependencies:

dev_dependencies:
  test: ^1.25.2
