name: aes_crypt_null_safe
description: Dart encryption library for encrypting/decrypting files, plain text and binary data in AES Crypt file format.
version: 2.0.1
homepage: https://github.com/CodingFries/aes_crypt_null_safe
repository: https://github.com/CodingFries/aes_crypt_null_safe

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:

dev_dependencies:
  test: ^1.18.0
