name: aes_crypt_null_safe
description: Dart encryption library for encrypting/decrypting files, plain text and binary data in AES Crypt file format. Supports all platforms including web.
version: 3.1.0
homepage: https://github.com/CodingFries/aes_crypt_null_safe
repository: https://github.com/CodingFries/aes_crypt_null_safe

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  universal_io: ^2.2.2

dev_dependencies:
  test: ^1.26.3
  flutter_lints: ^6.0.0

